### ISSUE TITLE
does not close old issue

### ISSUE THREAD

**Issue by apobekiaris** [probot/stale#150] opened 2018-08-03 08:40 UTC
I install it yesterday and add the default settings at https://github.com/expand/eXpand/blob/18.1/.github/stale.yml

I then reopen an old post from 2019
https://github.com/expand/eXpand/issues/11

and wait but nothing. How can I get more info on what is wrong?

**Comment by johlju** [comment] 2018-08-03 10:50
When you opened the issue you got activity on it, so according to your configuration it will be closed in 7 days (at least if it works setting `daysUntilClose` lower than `daysUntilStale`).

**Comment by apobekiaris** [comment] 2018-08-11 11:28
thnks for the answer we are now on 8th day with no activity but the issue is not close. What you think is happening?

**Comment by johlju** [comment] 2018-08-11 15:49
Normally the configuration is made so that the stale label is set, and after that, after the configured time the issue is closed. Since the issue hasn’t the stale label, maybe it won’t close the issue. 
If you configured it to label the issue after 7 days, and close it after 8 days. Will that work?

**Comment by expand** [comment] 2018-08-11 17:11
>If you configured it to label the issue after 7 days, and close it after 8 days

can you detail me on what exactly I have to configure?

**Comment by johlju** [comment] 2018-08-11 17:39
I would try this

```yml
daysUntilStale: 7
daysUntilClose: 8
```

**Comment by hiimbex** [comment] 2018-08-11 19:52
@apobekiaris you have:
```yml
daysUntilStale: 60
daysUntilClose: 7
```

The issue you linked won't get marked as stale unless there is no activity for 60 days in a row. You re-opened that issue 9 days ago, which counts as 'activity'. 

`daysUntilClose` is the number of days until an issue is close _after_ it has been marked as stale. In your case, it has not been 60 days yet, so the issue has not been marked yet. 

Closing since this is not an issue on stale's end.

**Closed by hiimbex** 2018-08-11 19:52 UTC
